# Secrets via sops-nix (#18). The repo is public, so NOTHING secret is committed in
# plaintext: secrets live in `secrets/` as sops ciphertext and are decrypted at
# ACTIVATION, on the unlocked machine, into tmpfs under /run.
#
# Every secret is encrypted to two recipients — the Admin age key and the Host age key.
# What each one is, why their lifetimes differ, and which loss is recoverable are all
# defined once in CONTEXT.md ("Admin age key" / "Host age key"); that is the canonical
# statement and is deliberately not restated here. The recipient list itself lives in
# `.sops.yaml` at the repo root — that is sops' own config, not a NixOS option.
#
# This file is the DECRYPTION half: how this machine gets at the secrets, and which
# secrets it declares. User-account policy lives with the account in default.nix.
{ lib, ... }:
let
  # How many age recipients the committed secret is actually encrypted to. The sops
  # format emits one `recipient:` line per age recipient, so counting them checks the
  # property we care about directly rather than through a proxy like grepping .sops.yaml
  # for a commented-out line.
  usersSecretRecipients = builtins.length (
    builtins.filter builtins.isList (
      builtins.split "recipient:" (builtins.readFile ../../secrets/users.yaml)
    )
  );
in
{
  # --- How this machine decrypts ---
  # sops-nix converts the ed25519 SSH host key into an age identity internally, so the
  # host needs no separate age keyfile to manage, back up, or leak. This is set EXPLICITLY
  # rather than left to the module default because that default is derived from
  # `services.openssh.enable`, which is deliberately OFF here (below).
  sops.age.sshKeyPaths = [ "/etc/ssh/ssh_host_ed25519_key" ];

  # NO sshd. `services.openssh.enable = true` is the usual way this host key comes to
  # exist, but enabling it would run a listening daemon on a single-user laptop purely as
  # a side effect of wanting a key file — a remote attack surface bolted onto a config
  # whose whole posture (ADR-0003, ADR-0005) is about minimising physical and local
  # exposure. We want the KEY, not the SERVER, so the key is generated standalone by
  # `ssh-keygen` during the install ritual (docs/hardware-acceptance.md).
  #
  # Deliberately NOT generated by an activation script (contrast home.nix, which does
  # generate the commit signing key that way). It would not help: a secret can only be
  # decrypted by a host age key that was already a RECIPIENT when the secret was
  # encrypted, so the key must exist — and `.sops.yaml` must already list it — BEFORE the
  # first activation that reads a secret. Generating it mid-activation would be too late
  # to decrypt anything, while making the config look self-bootstrapping when it isn't.
  # The chicken-and-egg is resolved by hand, once, in the installer. See #24.
  #
  # TRADE-OFF ACCEPTED: this puts the host age key outside declarative management —
  # nothing in the repo recreates it, and losing it means activation fails until the
  # secrets are re-keyed. That is the same bargain the sbctl PKI bundle already makes
  # (default.nix), and it is the price of not running a daemon we do not want.

  # The default file every `sops.secrets.<name>` below reads from unless it overrides
  # `sopsFile`. `sops.validateSopsFiles` is left at its default (true), so a build FAILS
  # loudly if this file is missing or is not actually sops-encrypted — the guard that
  # keeps a plaintext secret from ever silently passing for an encrypted one.
  sops.defaultSopsFile = ../../secrets/users.yaml;

  # --- Secret #1: drew's password hash (replaces the #16 placeholder) ---
  # `neededForUsers` is load-bearing, not a hint: it moves this secret to
  # /run/secrets-for-users and decrypts it EARLY, before NixOS creates users, because
  # `users.users.drew.hashedPasswordFile` (default.nix) is read during user creation.
  # A plain `sops.secrets` here would decrypt too late and the account would end up with
  # no valid password. Such secrets must be root-owned, which is the module default.
  #
  # It is a HASH, never a password: what is encrypted here is yescrypt output from
  # `mkpasswd`, so even a future compromise of both age keys yields a hash to crack, not a
  # credential to use. Generating it is a human step — see docs/hardware-acceptance.md.
  sops.secrets.drew_password_hash = {
    neededForUsers = true;
  };

  # --- Guard: is the Host age key actually a recipient yet? ---
  # Until the install ritual adds it (docs/hardware-acceptance.md, Phase B), secrets are
  # encrypted to the Admin age key ALONE — correct before the laptop exists, and a
  # guaranteed first-boot lockout after it does. That gap is otherwise invisible: eval and
  # build both stay green with one recipient, and the failure surfaces only at the first
  # activation, which is precisely the case with no earlier generation to roll back to.
  #
  # So it is surfaced as a build-time warning that clears itself the moment the ritual is
  # done. A warning and not an assertion on purpose: the one-recipient state is LEGITIMATE
  # today, and failing eval would block the very work that reaches the ritual.
  #
  # Only users.yaml is checked — it is the secret whose absence locks Drew out. When #4
  # adds secrets/secureboot.yaml it should extend this rather than add a second copy.
  warnings = lib.optional (usersSecretRecipients < 2) ''
    secrets/users.yaml is encrypted to ${toString usersSecretRecipients} recipient(s), expected 2.
    The Host age key is not a recipient yet, so this machine CANNOT decrypt drew's password
    at activation — and with users.mutableUsers = false that means no password works.
    This is expected until the laptop is installed. Before the first nixos-install, follow
    docs/hardware-acceptance.md ("Phase B"): generate the host key, ssh-to-age it, add it to
    .sops.yaml, then `sops updatekeys secrets/users.yaml` with the Admin age key.
  '';

  # --- Seam: the Secure Boot signing key (#4 / #21, ADR-0002) ---
  # The lanzaboote slice currently points `boot.lanzaboote.pkiBundle` at the on-device
  # sbctl bundle in /var/lib/sbctl, created by hand on the machine and NOT committed
  # anywhere — so today the Secure Boot signing key exists in exactly one place and dies
  # with the disk. ADR-0002 and CONTEXT.md both describe its long-term home as a sops
  # secret instead; they state that as fact, and it is not yet true. This slice provides
  # the mechanism, #4 does the wiring, and until then those two documents run ahead of
  # the config.
  #
  # What #4 needs from here is just the shape — the same two-recipient path as above:
  #
  #   sops.secrets."secureboot/db_key" = {
  #     sopsFile = ../../secrets/secureboot.yaml;   # its own file, not users.yaml
  #     mode = "0400";                              # root-only; sbctl signs as root
  #   };
  #
  # Note it must NOT set `neededForUsers` — it is not read during user creation, so it
  # belongs in the regular /run/secrets pass. The `.sops.yaml` creation rule already
  # covers `secrets/*.yaml`, so no recipient change is needed.
}
